a = input('Digite algo: ')
print('O tipo primitivo é:',type(a))
print('É um numero:',a.isnumeric())
print('So tem espaços:',a.isspace())
print('É alfabetico:',a.isalpha())
print('É alfanumerico:',a.isalnum())
print('Esta em maiusculas:',a.isupper())
print('Esta em minusculas:',a.islower())
print('Esta capitalizado:',a.istitle())
