n1 = float(input('Digite a primeira nota: '))
n2 = float(input('Digite a segunda nota: '))
n3 = float(input('Digite a terceira  nota: '))
n4 = float(input('Digite a quarta nota: '))
n5 = float(input('Digite a quinta nota: '))
print('Maravilha sua media final foi: {:.1f}'.format((n1+n2+n3+n4+n5)/5))